mainapp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('contact/', contact, name='contact'),
    path('azamattyq/', azamattyq, name='azamattyq'),
    path('info_zher/', zher, name='info_zher'),
    path('info_help/', help, name='info_help'),
    path('info_help/help', clienthelp, name='clienthelp'),
    path('about-us/', about, name='about'),
    path('news/', news, name='news'),
    path('data/', data, name='data'),
    path('request/', homerequest, name='homerequest'),
    path('vakancia/', vakancia, name='vakancia'),
    path('vakancia/otinish', vakanciaotinish, name='vakanciaotinish'),
    path('search_homes/', search_homes, name='search_homes'),
    path('news/<slug:slug>/', detailnews, name='detailnews'),
    path('search_homes/<slug:slug>/', detailhomes, name='detailhomes'),
    path('free_lands/', free_lands, name='free_lands'),
    path("addreview/", addreview, name="addreview"),
    path("question/", questions, name="question"),
    path("addquestion/", addquestion, name="addquestion"),
    path('contact/', contact, name='contact'),
]

migracia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models


class Home(models.Model):
    title = models.CharField('Титул', max_length=255)
    address = models.CharField('Адрес', max_length=255)
    description = models.TextField('Сипаттама')
    price = models.IntegerField('Бағасы', blank=True, null=True)
    slug = models.SlugField()
    image = models.ImageField('Сурет', upload_to='receive_housing/')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'homes'
        verbose_name = "Үй туралы мәлімет"
        verbose_name_plural = "Үй туралы мәліметтер"


class HomeShots(models.Model):
    title = models.CharField("Заголовок", max_length=100)
    image = models.ImageField("Изображение", upload_to="Home_shots/")
    vehicle = models.ForeignKey(Home, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        db_table = 'images_home'
        verbose_name = "Сурет"
        verbose_name_plural = "Суреттер"


class Jer(models.Model):
    name = models.CharField('Аты', max_length=255)
    rayon = models.CharField('Аудан', max_length=255)
    village = models.CharField('Ауыл', max_length=255)
    description = models.TextField('Сипаттама')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'zher'
        verbose_name = "Жер туралы мәлімет"
        verbose_name_plural = "Жер туралы мәліметер"


class Data(models.Model):
    title = models.CharField('Титул', max_length=255)
    description = models.TextField('Сипаттама')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'datasmodel'
        verbose_name = "Жалпы мәлімет"
        verbose_name_plural = "Жалпы мәліметер"


class CategoryNews(models.Model):
    name = models.CharField('Категория аты', max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'categorynews'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категориялар'


class News(models.Model):
    title = models.CharField('Тақырыбы', max_length=255)
    description = models.TextField('Мәтіні')
    image = models.ImageField('Сурет', upload_to='news/')
    slug = models.SlugField()
    yout = models.CharField('Жаңалыққа сілтеме', max_length=2000, null=True, blank=True)
    category = models.ForeignKey(CategoryNews, verbose_name='Категория', on_delete=models.CASCADE)
    created_at = models.DateTimeField('Жарияланған күні', auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'news'
        verbose_name = "Жаңалық"
        verbose_name_plural = "Жаңалықтар"


class Vakancia(models.Model):
    region = models.CharField('Аймақ', max_length=500)
    qyzmet = models.TextField('Қызмет')

    def __str__(self):
        return f"{self.region} - {self.qyzmet}"

    class Meta:
        db_table = 'vakancia'
        verbose_name = "Вакансия"
        verbose_name_plural = "Вакансиялар"


class RequestHelp(models.Model):
    ch = [
        ('Ақшалай', 'Ақшалай'),
        ('Жұмыс', 'Жұмыс'),
        ('Үй', 'Үй'),
        ('Гуманитарлық', 'Гуманитарлық'),
    ]
    name = models.CharField("Есіміңіз", max_length=100)
    surname = models.CharField("Тегіңіз", max_length=100)
    nomer = models.CharField("Телефон номер", max_length=11)
    req = models.CharField("Көмек түрі", choices=ch, max_length=100)
    email = models.EmailField()
    publish = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.name} - {self.email}"

    class Meta:
        db_table = 'requesthelp'
        verbose_name = "Әлеуметтік көмек"
        verbose_name_plural = "Әлеуметтік көмектер"


class OtinishVak(models.Model):
    name = models.CharField("Есіміңіз", max_length=100)
    surname = models.CharField("Тегіңіз", max_length=100)
    nomer = models.CharField("Телефон номер", max_length=11)
    vakancia = models.ForeignKey(Vakancia, verbose_name='Вакансия', on_delete=models.CASCADE)
    email = models.EmailField()
    publish = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.surname} - {self.email}"

    class Meta:
        db_table = 'otinishvak'
        verbose_name = "Бос жұмыс орындарына өтініш"
        verbose_name_plural = "Бос жұмыс орындарына өтініштер"


class Questions(models.Model):
    name = models.CharField("Есімі", max_length=100)
    text = models.TextField("Хабарлама", max_length=5000)

    email = models.EmailField()
    publish = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.email}"

    class Meta:
        db_table = 'questions'
        verbose_name = "Сұрақ"
        verbose_name_plural = "Сұрақтар"


class Reviews(models.Model):
    name = models.CharField("Есімі", max_length=100)
    surname = models.CharField("Тегі", max_length=100)
    email = models.EmailField()
    text = models.TextField("Хабарлама", max_length=5000)
    image = models.ImageField('Суреті', upload_to='reviews/', blank=True)
    publish = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.surname} -{self.email}"

    class Meta:
        db_table = 'reviews'
        verbose_name = "Пікір"
        verbose_name_plural = "Пікірлер"

mainapp/forms.py
from django import forms
from .models import Questions, Reviews, OtinishVak,RequestHelp


class QuestionsForm(forms.ModelForm):
    class Meta:
        model = Questions
        fields = ("name", "email", "text",)
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Есіміңіз"}),
            "email": forms.EmailInput(attrs={"class": "form-control border", "placeholder": "Почтаңыз"}),
            "text": forms.Textarea(attrs={"class": "form-control border", "placeholder": "Сұрағыңыз..."}),

        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ("name", "surname", "email", "text", "image")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Есіміңіз"}),
            "surname": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Тегіңіз"}),
            "email": forms.EmailInput(attrs={"class": "form-control border", "placeholder": "Почтаңыз"}),
            "text": forms.Textarea(attrs={"class": "form-control border", "placeholder": "Біз туралы пікіріңіз..."}),

        }


class OtinishVakForm(forms.ModelForm):
    class Meta:
        model = OtinishVak
        fields = ("name", "surname", "email", "nomer", "vakancia")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Есіміңіз"}),
            "surname": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Тегіңіз"}),
            "nomer": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Телефон номеріңіз"}),
            "email": forms.EmailInput(attrs={"class": "form-control border", "placeholder": "Почтаңыз"}),

        }

class RequestHelpForm(forms.ModelForm):
    class Meta:
        model = RequestHelp
        fields = ("name", "surname", "email", "nomer", "req")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Есіміңіз"}),
            "surname": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Тегіңіз"}),
            "nomer": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Телефон номеріңіз"}),
            "email": forms.EmailInput(attrs={"class": "form-control border", "placeholder": "Почтаңыз"}),

        }

mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import QuestionsForm, ReviewForm, OtinishVakForm, RequestHelpForm
from .models import *


def index(request):
    reviews = Reviews.objects.order_by('-publish')[:3]
    context = {'title': 'Басты бет', 'reviews': reviews}
    return render(request, 'mainapp/index.html', context)


def about(request):
    context = {'title': 'Біз туралы', }
    return render(request, 'mainapp/about-us.html', context)


def news(request):
    news = News.objects.order_by('-created_at')
    context = {'title': 'Жаңалықтар', 'news': news}
    return render(request, 'mainapp/news.html', context)


def search_homes(request):
    homes = Home.objects.all()
    context = {'title': 'Тұрғын үй іздеу', 'homes': homes}
    return render(request, 'mainapp/homes.html', context)


def detailnews(request, slug):
    question = get_object_or_404(News, slug=slug)
    context = {'new': question}
    return render(request, 'mainapp/news-details.html', context)


def detailhomes(request, slug):
    question = get_object_or_404(Home, slug=slug)
    context = {'home': question}
    return render(request, 'mainapp/homes-details.html', context)


def free_lands(request):
    context = {'title': 'ЖАО сайттарында шаруашылыққа бос жер туралы ақпарат'}
    return render(request, 'mainapp/free_lands.html', context)


def data(request):
    datas = Data.objects.all()
    context = {'title': 'Мәліметтер', 'datas': datas}
    return render(request, 'mainapp/data.html', context)


def vakancia(request):
    vakancia = Vakancia.objects.all()
    context = {'title': 'Мәліметтер', 'vakancia': vakancia}
    return render(request, 'mainapp/vakancia.html', context)


def vakanciaotinish(request):
    if request.method == 'POST':
        form = OtinishVakForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
            return redirect('home')
    form = OtinishVakForm()
    context = {
        'form': form,
        'title': 'Өтініш беру'
    }
    return render(request, 'mainapp/clientotinish.html', context)


def clienthelp(request):
    if request.method == 'POST':
        form = RequestHelpForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
            return redirect('home')
    form = RequestHelpForm()
    context = {
        'form': form,
        'title': 'Өтініш беру'
    }
    return render(request, 'mainapp/clienthelp.html', context)


def azamattyq(request):
    context = {'title': 'Азаматтық алу'}
    return render(request, 'mainapp/info_azamattyq.html', context)


def zher(request):
    jer = Jer.objects.all()
    context = {'title': 'Жер учаскесі', 'jer': jer}
    return render(request, 'mainapp/info_zher.html', context)


def help(request):
    context = {'title': 'Әлеуметтік көмек'}
    return render(request, 'mainapp/info_help.html', context)


def homerequest(request):
    otinishvak = OtinishVak.objects.order_by('-publish')
    reviews = Reviews.objects.order_by('-publish')
    requests = RequestHelp.objects.order_by('-publish')
    questions = Questions.objects.order_by('-publish')
    context = {'title': 'Өтініштер', 'otinishvak': otinishvak, 'requests': requests,
               'reviews': reviews, 'questions': questions}
    return render(request, 'mainapp/homerequest.html', context)


def contact(request):
    form = ReviewForm()
    context = {'title': 'Контактілер', 'form': form}

    return render(request, 'mainapp/contact.html', context)


def addreview(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
            return redirect('home')


def questions(request):
    form = QuestionsForm()
    context = {'title': 'Сұрағыңызды қойыңыз', 'form': form}

    return render(request, 'mainapp/raise_question.html', context)


def addquestion(request):
    if request.method == 'POST':
        form = QuestionsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
            return redirect('home')

templates/mainapp/about-us.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>

    <title>{% block title %}{{ title }}{% endblock title %}</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,500,600,700&display=swap" rel="stylesheet">


</head>
{% block content %}
<body>



    <!-- Breadcrumb Section Begin -->
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h2>Біз туралы</h2>
                        <div class="bt-option">
                            <a href="{% url 'home' %}">Басты бет</a>
                            <span>Біз туралы</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section End -->

    <!-- About Us Page Section Begin -->
    <section class="aboutus-page-section spad">
        <div class="container">
            <div class="about-page-text">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="ap-title">
                            <h2>Qandastar көші-қон орталығы</h2>
                            <p>2020 жылы құрылған бұл орталық Алматы қаласының орталығында орналасқан және 24/7 сіздерге қызмет көрсетуге дайын. Бұл орталық мынадай қызметтер ұсынады.</p>
                        </div>
                    </div>
                    <div class="col-lg-5 offset-lg-1">
                        <ul class="ap-services">
                            <li><i class="icon_check"></i> Бос жұмыс орындары</li>
                            <li><i class="icon_check"></i> Жұмысқа орналасуға өтініш</li>
                            <li><i class="icon_check"></i> Қандастар туралы мәлімет</li>
                            <li><i class="icon_check"></i> Үй іздеу</li>
                            <li><i class="icon_check"></i> Сұрақтарға жауап алу</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="about-page-services">
                <div class="row">
                    <div class="col-md-4">
                        <div class="ap-service-item set-bg" data-setbg="{% static 'img/about/kluch.jpg' %}">
                            <div class="api-text">
                                <h3>Тұрғын үй алу</h3>
                            </div>
                        </div>
                    </div>
                     <div class="col-md-4">
                        <div class="ap-service-item set-bg" data-setbg="{% static 'img/about/uchastok.jpg' %}">
                            <div class="api-text">
                                <h3>Жер учаскесі</h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="ap-service-item set-bg" data-setbg="{% static 'img/about/grajdan.jpg' %}">
                            <div class="api-text">
                                <h3>Азаматтық алу</h3>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <!-- About Us Page Section End -->

    <!-- Video Section Begin -->
    <section class="video-section set-bg" data-setbg="{% static 'img/back.jpeg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="video-text">
                        <p></p>
                        <h2>Біздің жүйе мен қызметтерімізбен танысыңыз.</h2>
                        <a href="https://www.youtube.com/watch?v=EzKkl64rRbM" class="play-btn video-popup"><img
                                src="img/play.png" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Video Section End -->

    <!-- Gallery Section Begin -->
    <section class="gallery-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <span>Біздің жүйе</span>
                        <h2>Бізде атқарылатын жұмыстар</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="gallery-item set-bg" data-setbg="{% static 'img/gallery/gallery2.png' %}">
                        <div class="gi-text">
                            <h3>Атаулы көмек</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="gallery-item set-bg" data-setbg="{% static 'img/gallery/gallery1.jpg' %}">
                                <div class="gi-text">
                                    <h3>Тұрғын үй</h3>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="gallery-item set-bg" data-setbg="{% static 'img/gallery/sel.jpg' %}">
                                <div class="gi-text">
                                    <h3>Шаруашылық</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="gallery-item large-item set-bg" data-setbg="{% static 'img/gallery/gallery3.jpg' %}">
                        <div class="gi-text">
                            <h3>Бос жұмыс орындары</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Gallery Section End -->



    <!-- Search model Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch"><i class="icon_close"></i></div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search model end -->

    <!-- Js Plugins -->
    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/jquery.nice-select.min.js"></script>
    <script src="js/jquery-ui.min.js"></script>
    <script src="js/jquery.slicknav.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/main.js"></script>
</body>
{% endblock content %}
</html>

templates/mainapp/clienthelp.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>

    <title>{% block title %}{{ title }}{% endblock title %}</title>


</head>

{% block content %}
<body>


<!-- Contact Section Begin -->
<section class="contact-section spad">
    <div class="container">
        <div class="row">

            <div class="col-lg-7 offset-lg-1">
                <h2>Өтініш формасы</h2>
                <form action="{% url 'clienthelp' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6">
                            {{ form.name }}<br>
                        </div>
                        <div class="col-lg-6">
                            {{ form.surname }}<br>
                        </div>
                        <div class="col-lg-12">
                            {{ form.email }}<br>
                        </div>
                        <div class="col-lg-12">
                            {{ form.req }}<br><br>
                        </div>
                        <div class="col-lg-12">
                            {{ form.nomer }}<br>
                            <button class="btn btn-info" type="submit">Жіберу</button>
                        </div>

                    </div>
                </form>
            </div>

        </div>

    </div>
</section>
<!-- Contact Section End -->

<!-- Search model Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch"><i class="icon_close"></i></div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>

</body>

{% endblock content %}
</html>

templates/mainapp/clientotinish.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>

    <title>{% block title %}{{ title }}{% endblock title %}</title>


</head>

{% block content %}
<body>


<!-- Contact Section Begin -->
<section class="contact-section spad">
    <div class="container">
        <div class="row">

            <div class="col-lg-7 offset-lg-1">
                <h2>Өтініш формасы</h2>
                <form action="{% url 'vakanciaotinish' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6">
                            {{ form.name }}<br>
                        </div>
                        <div class="col-lg-6">
                            {{ form.surname }}<br>
                        </div>
                        <div class="col-lg-12">
                            {{ form.email }}<br>
                        </div>
                        <div class="col-lg-12">
                            {{ form.vakancia }}<br><br>
                        </div>
                        <div class="col-lg-12">
                            {{ form.nomer }}<br>
                            <button class="btn btn-info" type="submit">Жіберу</button>
                        </div>

                    </div>
                </form>
            </div>

        </div>

    </div>
</section>
<!-- Contact Section End -->

<!-- Search model Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch"><i class="icon_close"></i></div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>

</body>

{% endblock content %}
</html>

templates/mainapp/data.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }}{% endblock title %}</title>
</head>
{% block content %}
<body>
<div class="container">
    <h2>Қажетті пунктті таңдап ақпарат алыңыз</h2>
    {% for data in datas %}
    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo{{ data.id }}">{{ data.title }}</button>
    <div id="demo{{ data.id }}" class="collapse">
        {% autoescape off %}
        {{ data.description }}
        {% endautoescape %}
    </div>
    <br>
    <br>
    {% endfor %}
</div>
</body>
{% endblock content %}
</html>

templates/mainapp/homes-details.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>

    <title>{% block title %}{{ home.title }}{% endblock title %}</title>


    <link href="https://fonts.googleapis.com/css?family=Lora:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,500,600,700&display=swap" rel="stylesheet">


</head>

{% block content %}
<body>
<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>


<!-- Breadcrumb Section Begin -->
<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <h2>{{ home.title }}</h2>
                    <div class="bt-option">
                        <a href="{% url 'home' %}">Басты бет</a>
                        <a href="{% url 'search_homes' %}">Тұрғын үй іздеу</a>
                        <span>{{ home.title }}</span>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Section End -->

<!-- Room Details Section Begin -->
<section class="room-details-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="room-details-item">
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            {% for image in home.homeshots_set.all %}
                            <div class="carousel-item {% if forloop.first %}active {% endif %} ">
                                <img class="d-block w-100" src="{{ image.image.url }}" alt="First slide">
                            </div>
                            {% endfor %}

                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
                           data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
                           data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>


                    <div class="rd-text">
                        <div class="rd-title">
                            <h3>{{ home.title }}</h3>

                            <hr>
                            <br>
                            <br>
                            <h4>Адрес:</h4>
                            <p class="f-para">
                            {{ home.address }}
                            </p>
                            <h4>Бағасы:</h4>
                            <p class="f-para">
                            {{ home.price }} тг
                            </p>
                            <p class="f-para">
                                {{ home.description }}
                            </p>
                        </div>
                    </div>

                </div>

            </div>
        </div>
</section>
<!-- Room Details Section End -->

<!-- Search model Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch"><i class="icon_close"></i></div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search model end -->


</body>
{% endblock content %}
</html>

templates/mainapp/homes.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>

    <title>{% block title %}{{ title }}{% endblock title %}</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,500,600,700&display=swap" rel="stylesheet">


</head>
{% block content %}
<body>


<!-- Breadcrumb Section Begin -->
<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <h2>Тұрғын үй іздеу</h2>
                    <div class="bt-option">
                        <a href="{% url 'home' %}">Басты бет</a>
                        <span>Тұрғын үй іздеу</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Section End -->

<!-- Blog Section Begin -->
<section class="blog-section blog-page spad">
    <div class="container">
        <div class="row">
            {% for home in homes %}
            <div class="col-lg-4 col-md-6">
                <a href="{% url 'detailhomes' home.slug %}">
                    <div class="blog-item set-bg" data-setbg="{{ home.image.url }}">
                        <div class="bi-text">
                            <span class="b-tag" style="background:#000000b3;">{{ home.price }}</span>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Blog Section End -->


<!-- Search model Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch"><i class="icon_close"></i></div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search model end -->


</body>
{% endblock content %}
</html>